version: '3'
services:
  bdo-api:
    image: bdo-api
    restart: always
    build:
      context: ./bdo-api
      dockerfile: ./Dockerfile
    networks:
      - network
    expose:
      - 8001

  ikusa-api:
    image: ikusa-api
    restart: always
    build:
      context: ./ikusa-api
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - network

networks:
  network: